# .platform.app.yaml
name: app
type: php:8.2

disk: 1024

mounts:
  "/app/var": "shared:files"

build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
hooks:
  deploy: |
    php bin/console doctrine:migrations:migrate --no-interaction
  post_deploy: |
    php bin/console doctrine:fixtures:load --no-interaction

variables:
  env:
    DATABASE_URL: "pgsql://main:main@database.internal:5432/main"


relationships:
  database: "postgresql:postgresql"

runtime:
  extensions:
    - pdo_pgsql

workers:
    messenger-consumer:
        commands:
            start: "php bin/console messenger:consume async --no-interaction"
