# .platform.app.yaml
name: app
type: php:8.2

disk: 1024

mounts:
  "/app/var": "shared:files"

build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]

hooks:
  deploy: |
    php bin/console doctrine:migrations:migrate --no-interaction

relationships:
  database: "postgresql:postgresql"

variables:
  env:
    DATABASE_URL: "pgsql://${PLATFORM_RELATIONSHIPS[database][username]}:${PLATFORM_RELATIONSHIPS[database][password]}@${PLATFORM_RELATIONSHIPS[database][host]}:${PLATFORM_RELATIONSHIPS[database][port]}/${PLATFORM_RELATIONSHIPS[database][path]}"

runtime:
  extensions:
    - pdo_pgsql