# .platform.app.yaml
name: app
type: php:8.2

disk: 1024

mounts:
  "/app/var": "shared:files"

build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]

hooks:
  deploy: |
    php bin/console doctrine:migrations:migrate --no-interaction

relationships:
  database: "postgresql:postgresql"

variables:
  env:
    DATABASE_URL: "pgsql://{default.username}:{default.password}@{default.host}:{default.port}/{default.path}"

runtime:
  extensions:
    - pdo_pgsql