# .platform.app.yaml
name: app
type: php:8.2

build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]

hooks:
  deploy: |
    php bin/console doctrine:migrations:migrate --no-interaction

relationships:
  database: "postgresql:postgresql"
