# .platform.app.yaml
name: app
type: php:8.2

disk: 1024

mounts:
  "/app/var": "shared:files"

build:
  flavor: composer

web:
  locations:
    "/":
      root: "public"
      index: ["index.php"]

hooks:
  deploy: |
    php bin/console doctrine:migrations:migrate --no-interaction

relationships:
  database: "postgresql:postgresql"

variables:
  env:
    DATABASE_URL: "pgsql://$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r .database[0].username):$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r .database[0].password)@$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r .database[0].host):$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r .database[0].port)/$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r .database[0].path)"

runtime:
  extensions:
    - pdo_pgsql