parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/tasks'
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $stripeSecretKey: '%env(string:STRIPE_SECRET_KEY)%'
            $stripePublicKey: '%env(string:STRIPE_PUBLIC_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
