parameters:
    uploads_directory: '/mnt/uploads/tasks'
    locale: 'fr'
    base_url: 'https://main-bvxea6i-zkvc3qbnbenee.fr-3.platformsh.site'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $stripeSecretKey: '%env(string:STRIPE_SECRET_KEY)%'
            $stripePublicKey: '%env(string:STRIPE_PUBLIC_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
